"""
摘要记忆（步骤 15）
多轮对话时，最近 4 轮完整保留，更早轮次压缩到 conversation.summary
"""
# TODO: 步骤 15 实现
# def build_summary_prompt(messages: list[dict]) -> str: ...
# def should_summarize(message_count: int) -> bool: ...
# def build_memory_context(conversation: dict, recent_messages: list[dict]) -> str: ...
