[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts = -ra --strict-markers --cov=routers --cov=utils --cov-config=tests/.coveragerc --cov-report=term-missing --cov-report=html:tests/htmlcov --cov-report=xml:tests/coverage.xml
filterwarnings =
    ignore:pkg_resources is deprecated as an API:UserWarning
